export const shopCategories = [
  { value: "electronics", label: "Electronics & Gadgets" },
  { value: "restaurant", label: "Restaurants & Cafes" },
  { value: "clothing", label: "Clothing & Apparel" },
  { value: "footwear", label: "Footwear & Accessories" },
  { value: "jewelry", label: "Jewelry & Watches" },
  { value: "beauty", label: "Beauty & Cosmetics" },
  { value: "health", label: "Health & Wellness" },
  { value: "pharmacy", label: "Pharmacies & Drugstores" },
  { value: "grocery", label: "Grocery & Supermarkets" },
  { value: "convenience", label: "Convenience Stores" },
  { value: "bakery", label: "Bakeries & Patisseries" },
  { value: "butcher", label: "Butcher & Meat Shops" },
  { value: "seafood", label: "Seafood Markets" },
  { value: "furniture", label: "Furniture & Home Decor" },
  { value: "hardware", label: "Hardware & Tools" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "automotive", label: "Automotive & Repair" },
  { value: "motorcycle", label: "Motorcycles & Scooters" },
  { value: "bicycle", label: "Bicycles & Cycling" },
  { value: "books", label: "Books & Stationery" },
  { value: "toys", label: "Toys & Games" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "outdoor", label: "Outdoor & Camping" },
  { value: "pet", label: "Pet Supplies & Services" },
  { value: "veterinary", label: "Veterinary Clinics" },
  { value: "flower", label: "Flowers & Gifts" },
  { value: "gift", label: "Gift Shops" },
  { value: "art", label: "Art Galleries & Studios" },
  { value: "craft", label: "Crafts & Hobbies" },
  { value: "music", label: "Music & Instruments" },
  { value: "movies", label: "Movies & Entertainment" },
  { value: "games", label: "Video Games & Arcades" },
  { value: "hotel", label: "Hotels & Accommodation" },
  { value: "travel", label: "Travel Agencies" },
  { value: "bank", label: "Banks & Financial Services" },
  { value: "insurance", label: "Insurance Agencies" },
  { value: "realestate", label: "Real Estate & Property" },
  { value: "education", label: "Education & Tutoring" },
  { value: "training", label: "Training & Workshops" },
  { value: "fitness", label: "Gyms & Fitness Centers" },
  { value: "spa", label: "Spas & Massage" },
  { value: "salon", label: "Hair & Nail Salons" },
  { value: "barber", label: "Barbershops" },
  { value: "laundry", label: "Laundry & Dry Cleaning" },
  { value: "repair", label: "Repair & Maintenance" },
  { value: "cleaning", label: "Cleaning Services" },
  { value: "printing", label: "Printing & Copying" },
  { value: "photography", label: "Photography Studios" },
  { value: "event", label: "Event Planning & Venues" },
  { value: "catering", label: "Catering Services" },
  { value: "fastfood", label: "Fast Food & Takeaway" },
  { value: "bar", label: "Bars & Pubs" },
  { value: "coffee", label: "Coffee Shops" },
  { value: "icecream", label: "Ice Cream & Desserts" },
  { value: "organic", label: "Organic & Health Foods" },
  { value: "wine", label: "Wine & Liquor Stores" },
  { value: "specialty", label: "Specialty Foods" },
  { value: "department", label: "Department Stores" },
  { value: "outlet", label: "Outlet Stores" },
  { value: "mall", label: "Shopping Malls" },
  { value: "market", label: "Markets & Bazaars" },
  { value: "online", label: "Online Stores" },
  { value: "secondhand", label: "Secondhand & Thrift" },
  { value: "antique", label: "Antiques & Collectibles" },
  { value: "religious", label: "Religious & Spiritual" },
  { value: "charity", label: "Charity & Non-Profit" },
  { value: "government", label: "Government Services" },
  { value: "postal", label: "Postal & Courier" },
  { value: "telecom", label: "Telecom & Mobile" },
  { value: "computer", label: "Computer & IT Services" },
  { value: "office", label: "Office Supplies" },
  { value: "security", label: "Security & Surveillance" },
  { value: "storage", label: "Storage & Moving" },
  { value: "parking", label: "Parking & Garages" },
  { value: "carwash", label: "Car Wash & Detailing" },
  { value: "rental", label: "Rental Services" },
  { value: "vending", label: "Vending Machines" },
  { value: "other", label: "Other" }
];